<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERBossTrackerJP.Core\ERBossTrackerJP.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\eventflag_bst.txt"
                      LogicalName="ERBossTrackerJP.Save.Data.eventflag_bst.txt" />
  </ItemGroup>

</Project>
